server:
  port: 8080
logging.level.tk.mybatis: TRACE
spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/mybase?characterEncoding=UTF-8
  username: root
  password: 123
  driver-class-name: com.mysql.jdbc.Driver
  druid : 
    initial-size: 2
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    stat-view-servlet.allow: true
mybatis : 
  type-aliases-package: com.tdhy.domain.entity
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.tdhy.util.mapper.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count = countSql

spring.redis:
    host : 127.0.0.1
    password : 
    port : 6379